### PR TITLE
Fix for Windows backslashes

### PR DESCRIPTION
**Pull request by astrotim**
added replace method to swap out Windows backslashes for Unix forward slashes

### CODE REVIEW

**Comment by astrotim** [comment]
any plans to add this Windows fix?

**Comment by eduardoboucas** [comment]
Sorry for the incredibly slow response. Will publish to npm shortly.

**Comment by eduardoboucas** [comment]
(And thanks!)

**Comment by astrotim** [comment]
Thank _you_! This package has been really helpful to our project.

**Comment by eduardoboucas** [comment]
Done! I'm glad you're finding it useful.

I haven't had much time to dedicate to it, so I really appreciate an extra set of hands. :)

**Pull request merged**
